name: Python package pipeline
on:
  push:
    tags:
    - '*'
jobs:
  build:
    name: Flake8, Pytest, Build package and publish to Github and PyPI
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.1.7
      - name: Setup Python 3.9
        uses: actions/setup-python@v5.2.0
        with:
          python-version: 3.9
      - name: Install package and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install -e .
      # - name: Run flake8 static analysis
      #   uses: suo/flake8-github-action@releases/v1
      #   with:
      #     checkName: 'test-build-publish'   # NOTE: this needs to be the same as the job name
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build a binary wheel and a source tarball
        run: python -m build
      - name: Upload wheel file
        uses: actions/upload-artifact@v4.4.0
        with:
          name: wheel
          path: dist/**
      - name: Determine tag
        id: determine_tag
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Release to Github
        id: create_release
        uses: ncipollo/release-action@v1.14.0
        with:
          name: ${{ steps.determine_tag.outputs.tag }}
          draft: false
          prerelease: false
          artifacts: dist/*
